name: ci

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      -
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'
      -
        run: pipenv install --dev
      -
        name: Test
        run: make test
