name: Build

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install dependencies
        with:
          python-version: '3.10'
          cache: 'pipenv'
        run: pip install --upgrade pip && pip install pipenv && pipenv install --dev
      -
        name: Test
        run: make test
